### ISSUE TITLE
Windows OVE-Electron does not load sequence on start

### ISSUE THREAD

**Issue by jdmccauley** [TeselaGen/ove-electron#40]
Hey, @tnrich ,

I use OVE-Electron on both Windows and Mac. On Mac, I appreciate that trying to open a sequence file type (ex: `.gb`) that I chose OVE-Electron to be my default viewer for, OVE-Electron starts in a new window with the sequence loaded. This does not occur on Windows however. On Windows, if I try to open a sequence file with OVE-Electron set as my default viewer, OVE-Electron just starts with no sequence loaded. I can import my sequence file just fine, but it's more effort than just 'double clicking' my sequence file and OVE-Electron loading it like it does on Mac.

For reference:
Version = 1.3.0
Install source: Windows Store

Best,
Josh

**Comment by tnrich** [comment]
@jdmccauley would you mind opening the devtools on your windows machine after trying to open a sequence and see if you're getting any errors or messages logged out to the console?

Should be under `View > Toggle Developer Tools` I think..?

Thanks!

**Comment by jdmccauley** [comment]
@tnrich 

There's no errors that seem relevant to me...

I attached a video showing this behavior. On Mac, double clicking the gb file opens it in OVE Electron on start, whereas on Windows 10 I have to 'Import Sequence' no matter what.


https://user-images.githubusercontent.com/22922096/182716627-8986d90b-c622-4251-bead-d1557cff0da5.mp4

**Comment by tnrich** [comment]
@jdmccauley would you mind checking if the latest version 1.4.1 fixes this issue for you? Thanks!

**Comment by jdmccauley** [comment]
@tnrich 
Just checked, unfortunately it does not.

**Comment by tnrich** [comment]
@0xpsi  @jdmccauley darn I thought I'd fixed this.. I'll look into this issue when I get a spare moment..

**Comment by tnrich** [comment]
@0xpsi want to try out this release and let me know if it works for you? - https://github.com/TeselaGen/ove-electron/releases/tag/v1.4.3 

@jdmccauley I'm working on releasing the windows version now

**Comment by jdmccauley** [comment]
Sounds great, thanks @tnrich!

**Comment by 0xpsi** [comment]
> @0xpsi want to try out this release and let me know if it works for you? - https://github.com/TeselaGen/ove-electron/releases/tag/v1.4.3
> 
> @jdmccauley I'm working on releasing the windows version now

Still unable to get it to work, although I may be doing something wrong. After downloading the .AppImage and making it executable, all I did was create a desktop shortcut in /usr/share/applications but not sure how to "install" it any other way. If I right click and "open with" it does not pop up as an option. Is there a particular way to "install" this? I'm on ubuntu 22

**Comment by tnrich** [comment]
@0xpsi what happens when you double click the desktop shortcut you made? Does it launch the tool correctly? I am not familiar with how Linux does things. It seems like it not popping up as an option is perhaps not an issue with ove-electron?  

I would expect that ove-electron would at least be an option for opening .gb files from a right click menu but that it would fail at the moment of trying to open it.

**Comment by 0xpsi** [comment]
@tnrich double clicking on the .Appimage file works fine, as well as the desktop shortcut I manually made. Right clicking on .gb files does not show OVE as an option. I believe it was showing as an option when I had it installed as a snap package, but was still only opening a blank file and not the .gb file.

**Comment by tnrich** [comment]
Ok, made a new release that hopefully simplifies the installation process. Basically I pulled the app from the various app stores and am no longer doing any sort of code signing or notarization (since those processes took soooo long to complete it made it difficult to iterate and fix bugs). 

The installation instructions and downloads for the latest version (mac/win/linux) can be found here: https://github.com/TeselaGen/ove-electron/releases/tag/v1.5.0

Please let me know if it solves the issues you were seeing @0xpsi and @jdmccauley 

Also @0xpsi the linux version icon is messed up right now but that should be fixable in a later release.

**Comment by 0xpsi** [comment]
@tnrich there is arm architecture available but maybe you forgot to include the amd64 also? thanks

**Comment by tnrich** [comment]
@0xpsi whoops didn't even realize that was an option for linux. Makes sense. I'll try to cut a new release with both architectures supported.

**Comment by tnrich** [comment]
@0xpsi ok I updated the release again, please try one more time here https://github.com/TeselaGen/ove-electron/releases/tag/v1.5.0

**Comment by 0xpsi** [comment]
@tnrich great, after installing the amd64 version I am able to open .gb files directly now! I am able to see the icon also.

However one issue now, (unrelated) but it appears it is not saving settings between states now (dark/light theme as well as custom enzyme groups)

**Comment by tnrich** [comment]
>However one issue now, (unrelated) but it appears it is not saving settings between states now (dark/light theme as well as custom enzyme groups)

@0xpsi what do you mean by `saving settings between states` exactly? Between closing and reopening the app? 

It seems to be persisting theme and custom enzyme groups for me on Ubuntu running on an ARM architecture. Please open a new issue if you continue to have issues. Thanks! Once @jdmccauley responds we can close this one.

**Comment by 0xpsi** [comment]
@tnrich yes between closing and reopening, and yeah I will create a new issue soon

**Comment by jdmccauley** [comment]
@tnrich will do soon, sorry I am working from home with my mac. I'll test it when I get to the office where my windows machine lives!

**Comment by jdmccauley** [comment]
@tnrich The windows install fails because it cannot find the installed .exe after setup. This fails both non-admin and admin setup runs.
![image](https://user-images.githubusercontent.com/22922096/196508104-005fe415-f404-49bc-ae46-9e3c36196fb9.png)

**Comment by tnrich** [comment]
Hmm @jdmccauley that is interesting. What version of windows are you on? And how are you installing? Could you provide a few more screenshots of your install process and what happens? 

I was able to download the .exe file on Windows 11 and open it and install it and it seemed to work for me. I'll ask a coworker with a windows machine to try as well.

**Comment by jdmccauley** [comment]
Here's my system info:

Edition	Windows 10 Pro
Version	21H2
Installed on	‎4/‎16/‎2021
OS build	19044.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0

Sorry I'm trying to hold out against Windows 11 as long as I can...

More pics:
![image](https://user-images.githubusercontent.com/22922096/196554135-b7c08a13-a551-4f60-a760-7216ab53d5ef.png)
![image](https://user-images.githubusercontent.com/22922096/196554280-a411c4d7-b974-4ce5-8f29-35c852176650.png)

It gets to the end of the progress bar really fast.
Then this:
![image](https://user-images.githubusercontent.com/22922096/196554374-fe48cd58-3bb1-4385-9391-a5fa1d51fb9c.png)

Calling 'Fix it':
![image](https://user-images.githubusercontent.com/22922096/196554430-fc266887-feb7-493a-9970-9058bc10bdbc.png)

**Comment by Norde** [comment]
Hi There,

Same problem than @jdmccauley regarding the windows installer. I opened a dedicated issue #53.


Regarding the initial topic, ie: that ove does not open .bg file on start (following a double click on .gb file or a right click "open with ove"):

Here is the output in the Dev console following this failure with ove 1.4.2 from MS store (the 1.5.5 cannot be installed on windows as mentioned above):

> use-local-storage-state - Error getting stored value, using defaultValue instead: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSON (storage.js:63:1)
    at Object.get (storage.js:24:1)
    at useLocalStorageState.js:139:50
    at Object.useMemo (react-dom.production.min.js:172:113)
    at exports.useMemo (react.production.min.js:23:102)
    at useClientLocalStorageState (useLocalStorageState.js:138:19)
    at useLocalStorageState (useLocalStorageState.js:59:1)
    at useMeltingTemp (useMeltingTemp.js:4:10)
    at index.js:82:31 null
